document.getElementById('language-selector').addEventListener('change', function() {
    var selectedLanguage = this.value;

    if (selectedLanguage === 'pt-br') {
        document.querySelector('.apresentacao__conteudo__titulo').innerText = "HISTÓRIA DO BROOKLYN NETS";

        document.getElementById('p1').innerText = "O Brooklyn Nets é um dos times mais icônicos da NBA, não apenas pelo talento em quadra, mas também por sua profunda conexão com a rica cultura e história do Brooklyn. Fundado em 1967 como New Jersey Americans e mais tarde conhecido como New Jersey Nets, o time mudou-se para o Barclays Center, no coração do Brooklyn, em 2012. Desde então, a franquia abraçou a autenticidade e o espírito criativo do bairro, tornando o Brooklyn Nets mais do que apenas um time de basquete - é um símbolo cultural.";

        document.getElementById('p2').innerText = "O Brooklyn possui uma herança cultural vibrante, marcada pela inovação, estilo único e música. No hip-hop, a influência do bairro é inconfundível, com artistas como The Notorious B.I.G., nascido e criado lá, representando a alma do lugar em sua música. Biggie foi um pioneiro do rap, e seu trabalho ainda ressoa como inspiração para muitas gerações. A presença de B.I.G. é constantemente associada aos Nets, refletindo a energia e perseverança que ele representava. Essa conexão é tão significativa que os Nets homenagearam Biggie com uma edição especial do uniforme City Edition, celebrando sua influência.";

        document.getElementById('p3').innerText = "Jean-Michel Basquiat, um dos artistas mais icônicos e revolucionários dos anos 1980, também nasceu e cresceu no Brooklyn. Sua arte, conhecida pela crítica ao racismo e às desigualdades sociais, mesclava graffiti e neoexpressionismo e continua sendo uma referência global no cenário das artes visuais. Os Nets utilizam a estética de Basquiat para homenagear a resiliência e a luta de sua comunidade, trazendo elementos que conectam o time à arte urbana e à liberdade criativa do Brooklyn. Basquiat também foi celebrado com um uniforme City Edition, que exibe seu estilo icônico e cores vibrantes.";

        document.getElementById('p4').innerText = "KAWS, outro artista influente, também contribui para essa vibração criativa. Famoso por seus personagens e formas distintas, KAWS incorpora o estilo urbano e inovador do Brooklyn, celebrado pelos Nets em seu design e estilo, com referências visuais que trazem modernidade e atitude à identidade do time. Os Nets lançaram um uniforme City Edition inspirado em KAWS, desenhado pelo próprio artista, que também criou uma arte especial para o chão da quadra quando o time usasse essa jersey. Essa colaboração única une basquete e arte contemporânea, reforçando ainda mais a identidade cultural do Brooklyn e a conexão profunda do time com a criatividade e o espírito da comunidade.";

        document.getElementById('p5').innerText = "A influência do hip-hop e da arte urbana é uma característica fundamental da cultura do Brooklyn, e os Nets conseguem refletir essa identidade autêntica. Através de seus uniformes, campanhas e colaborações com artistas, o Brooklyn Nets homenageia a tradição de um bairro que é um dos berços da cultura urbana, enquanto se posiciona como um time moderno e dinâmico com forte conexão com sua comunidade.";

        document.getElementById('p6').innerText = "O Brooklyn Nets venceu o título da Conferência Leste duas vezes, em 2002 e 2003, quando ainda eram conhecidos como New Jersey Nets. Nessas ocasiões, o time chegou às Finais da NBA, mas foi derrotado em ambas as séries, enfrentando o Los Angeles Lakers em 2002 e o San Antonio Spurs em 2003. Desde então, os Nets têm trabalhado arduamente para alcançar novos marcos e trazer um título da NBA para o Brooklyn, incorporando a resiliência e energia da comunidade que representam. O apoio de seus fãs e a forte conexão cultural com o bairro continuam a impulsionar os Nets em sua busca por novas conquistas.";
    } else {
        document.querySelector('.apresentacao__conteudo__titulo').innerText = "BROOKLYN NETS HISTORY";
        
        document.getElementById('p1').innerText = "The Brooklyn Nets is one of the most iconic teams in the NBA, not only for their talent on the court but also for their deep connection with the rich culture and history of Brooklyn. Founded in 1967 as the New Jersey Americans and later known as the New Jersey Nets, the team moved to the Barclays Center in the heart of Brooklyn in 2012. Since then, the franchise has embraced the authenticity and creative spirit of the borough, making the Brooklyn Nets more than just a basketball team - it is a cultural symbol.";

        document.getElementById('p2').innerText = "Brooklyn has a vibrant cultural heritage marked by innovation, unique style, and music. In hip-hop, the borough's influence is unmistakable, with artists like The Notorious B.I.G., born and raised there, representing the soul of the place in his music. Biggie was a rap pioneer, and his work still resonates as an inspiration for many generations. B.I.G.'s presence is constantly linked to the Nets, reflecting the energy and perseverance he embodied. This connection is so significant that the Nets have honored Biggie with a special City Edition jersey, celebrating his influence.";

        document.getElementById('p3').innerText = "Jean-Michel Basquiat, one of the most iconic and revolutionary artists of the 1980s, was also born and raised in Brooklyn. His art, known for its critique of racism and social inequalities, blended graffiti and neo-expressionism, and remains a global reference in the visual arts scene. The Nets use Basquiat's aesthetic to honor the resilience and struggle of their community, bringing elements that connect the team to urban art and Brooklyn's creative freedom. Basquiat was also celebrated with a City Edition jersey, featuring his iconic style and vibrant colors.";

        document.getElementById('p4').innerText = "KAWS, another influential artist, also contributes to this creative vibe. Famous for his distinctive characters and forms, KAWS embodies Brooklyn's urban and innovative style, celebrated by the Nets in their design and style, with visual references that bring modernity and attitude to the team's identity. The Nets released a City Edition jersey inspired by KAWS, designed by the artist himself, who also created a special artwork for the court floor whenever the team wore this jersey. This unique collaboration merges basketball with contemporary art, further reinforcing Brooklyn's cultural identity and the team's deep connection to the creativity and spirit of the community.";

        document.getElementById('p5').innerText = "The influence of hip-hop and urban art is a fundamental characteristic of Brooklyn culture, and the Nets manage to reflect this authentic identity. Through their uniforms, campaigns, and collaborations with artists, the Brooklyn Nets honor the tradition of a borough that is one of the birthplaces of urban culture, while positioning themselves as a modern, dynamic team with a strong connection to their community.";

        document.getElementById('p6').innerText = "The Brooklyn Nets won the Eastern Conference title twice, in 2002 and 2003, when they were still known as the New Jersey Nets. On these occasions, the team reached the NBA Finals but was defeated in both series, facing the Los Angeles Lakers in 2002 and the San Antonio Spurs in 2003. Since then, the Nets have worked hard to reach new milestones and bring an NBA title to Brooklyn, embodying the resilience and energy of the community they represent. The support of their fans and the strong cultural connection with the borough continue to drive the Nets in their pursuit of new achievements.";
    }
});